// Transpiled from COBOL program: PRG1
// Generated by Easy COBOL Migrator on 2026-03-23 06:13:40

#include <iostream>
#include <cstdlib>
#include <cstdint>

namespace prg1 {

int64_t return_code = 0;

} // namespace prg1

int main() {
    using namespace prg1;
    std::cout << "HELLO WORLD!" << std::endl;
    exit(0);
}
