// Transpiled from COBOL program: EDITED-NUM-TEST
// Generated by Easy COBOL Migrator on 2026-03-23 05:38:21

#include <iostream>
#include <string>
#include <cmath>
#include <cstdlib>
#include <vector>
#include <cstdint>
#include <cstdio>

// COBOL string move helper: truncate or right-pad to field width
inline std::string cobolMove(const std::string& src, int len) {
    std::string r = src; r.resize(len, ' '); return r;
}

// COBOL string comparison: pad shorter operand with spaces
inline int cobolCmp(const std::string& a, const std::string& b) {
    size_t len = std::max(a.size(), b.size());
    std::string la = a, lb = b;
    la.resize(len, ' '); lb.resize(len, ' ');
    return la.compare(lb);
}

// COBOL numeric display: sign, zero-padded integer digits, exact decimal places
inline std::string cobolPicFmt(double val, int intDigits, int decPlaces, bool isSigned) {
    char buf[64];
    if (decPlaces > 0) {
        int w = intDigits + 1 + decPlaces + (isSigned ? 1 : 0);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*.*f" : "%0*.*f", w, decPlaces, val);
    } else {
        auto iv = static_cast<long long>(val);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*lld" : "%0*lld", intDigits + (isSigned ? 1 : 0), iv);
    }
    return std::string(buf);
}
inline std::string cobolPicFmt(int val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}
inline std::string cobolPicFmt(int64_t val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}

// COBOL edited numeric display: apply PIC edit mask (Z, *, $, +, -)
inline std::string cobolEditFmt(double value, const std::string& pic) {
    // Expand PIC notation e.g. Z(3) -> ZZZ
    std::string exp;
    for (size_t i = 0; i < pic.size(); i++) {
        char ch = std::toupper(pic[i]);
        if (i+1 < pic.size() && pic[i+1] == '(') {
            size_t cl = pic.find(')', i+2);
            if (cl != std::string::npos) { int n = std::stoi(pic.substr(i+2, cl-i-2)); exp.append(n, ch); i = cl; continue; }
        }
        exp += ch;
    }
    // Determine floating symbol ($, +, - appearing 2+ times)
    char floatSym = 0; int floatCnt = 0;
    for (char c : exp) { if (c=='$'||c=='+'||c=='-') { if (!floatSym||floatSym==c) { floatSym=c; floatCnt++; } } }
    if (floatCnt < 2) floatSym = 0;
    // Build slot list and count digit positions
    struct Slot { char type; bool isDig; };
    std::vector<Slot> slots; int nDig = 0; int decAt = -1;
    for (char c : exp) {
        if (c=='9'||c=='Z'||c=='*') { slots.push_back({c,true}); nDig++; }
        else if ((c=='$'||c=='+'||c=='-') && floatSym==c) { slots.push_back({c,true}); nDig++; }
        else if (c=='V') { decAt = nDig; }
        else if (c=='.') { decAt = nDig; slots.push_back({'.',false}); }
        else if (c==','||c=='/'||c=='B'||c=='0') { slots.push_back({c,false}); }
        else if ((c=='$'||c=='+'||c=='-') && floatSym!=c) { slots.push_back({c,false}); }
    }
    if (decAt < 0) decAt = nDig;
    int decDig = nDig - decAt;
    // Build digit string
    bool neg = value < 0; double av = std::abs(value);
    long long sc = static_cast<long long>(std::round(av * std::pow(10.0, decDig)));
    std::string digs = std::to_string(sc);
    while ((int)digs.size() < nDig) digs = "0" + digs;
    if ((int)digs.size() > nDig) digs = digs.substr(digs.size() - nDig);
    // First significant digit
    int fSig = nDig;
    for (int i = 0; i < nDig; i++) { if (digs[i]!='0') { fSig=i; break; } }
    // Float insertion position
    int fPos = -1;
    if (floatSym) {
        int lastF = -1, di = 0;
        for (auto& s : slots) { if (s.isDig) { if (s.type==floatSym) lastF=di; di++; } }
        fPos = (fSig > 0 && lastF >= 0) ? std::min(fSig-1, lastF) : (fSig==nDig ? lastF : -1);
    }
    // Build result
    std::string res; int di = 0; bool seen = false;
    for (auto& s : slots) {
        if (s.isDig) {
            char d = digs[di]; bool lz = !seen && d=='0';
            if (s.type=='9') { res+=d; seen=true; }
            else if (s.type=='Z') { res+=(lz?' ':d); if(!lz) seen=true; }
            else if (s.type=='*') { res+=(lz?'*':d); if(!lz) seen=true; }
            else { if (di==fPos) { res+=(s.type=='$'?'$':(neg?'-':(s.type=='+'?'+':' '))); seen=true; }
                   else if (lz) res+=' '; else { res+=d; seen=true; } }
            di++;
        } else {
            if (s.type=='.') res+='.';
            else if (s.type==',') res+=(seen?',':' ');
            else if (s.type=='/') res+='/';
            else if (s.type=='B') res+=' ';
            else if (s.type=='0') res+='0';
            else if (s.type=='$') res+='$';
            else if (s.type=='+'||s.type=='-') res+=(neg?'-':(s.type=='+'?'+':' '));
        }
    }
    return res;
}

namespace edited_num_test {

// WORKING-STORAGE variables
double ws_amount = 12345.67;
double ws_small = 42.50;
double ws_zero = 0;
double ws_negative = -1234.56;
std::string ws_edit1 = cobolEditFmt(0.0, "-ZZ,ZZ9.99");
std::string ws_edit2 = cobolEditFmt(0.0, "$$$,$$9.99");
std::string ws_edit3 = cobolEditFmt(0.0, "*(5)9.99");
std::string ws_edit4 = cobolEditFmt(0.0, "ZZ,ZZ9.99");
std::string ws_bwz = cobolEditFmt(0.0, "ZZ,ZZ9.99");

int64_t return_code = 0;

} // namespace edited_num_test

int main() {
    using namespace edited_num_test;
    std::cout << "=== EDITED NUMERIC TESTS ===" << std::endl;
    ws_edit1 = cobolEditFmt(static_cast<double>(ws_amount), "-ZZ,ZZ9.99");
    std::cout << "Edit1 (large):  [" << ws_edit1 << "]" << std::endl;
    ws_edit1 = cobolEditFmt(static_cast<double>(ws_small), "-ZZ,ZZ9.99");
    std::cout << "Edit1 (small):  [" << ws_edit1 << "]" << std::endl;
    ws_edit1 = cobolEditFmt(static_cast<double>(ws_negative), "-ZZ,ZZ9.99");
    std::cout << "Edit1 (neg):    [" << ws_edit1 << "]" << std::endl;
    ws_edit2 = cobolEditFmt(static_cast<double>(ws_amount), "$$$,$$9.99");
    std::cout << "Edit2 (large):  [" << ws_edit2 << "]" << std::endl;
    ws_edit2 = cobolEditFmt(static_cast<double>(ws_small), "$$$,$$9.99");
    std::cout << "Edit2 (small):  [" << ws_edit2 << "]" << std::endl;
    ws_edit3 = cobolEditFmt(static_cast<double>(ws_amount), "*(5)9.99");
    std::cout << "Edit3 (large):  [" << ws_edit3 << "]" << std::endl;
    ws_edit3 = cobolEditFmt(static_cast<double>(ws_small), "*(5)9.99");
    std::cout << "Edit3 (small):  [" << ws_edit3 << "]" << std::endl;
    ws_edit4 = cobolEditFmt(static_cast<double>(ws_amount), "ZZ,ZZ9.99");
    std::cout << "Edit4 (large):  [" << ws_edit4 << "]" << std::endl;
    ws_edit4 = cobolEditFmt(static_cast<double>(ws_small), "ZZ,ZZ9.99");
    std::cout << "Edit4 (small):  [" << ws_edit4 << "]" << std::endl;
    ws_bwz = (ws_zero == 0) ? std::string(8, ' ') : cobolEditFmt(static_cast<double>(ws_zero), "ZZ,ZZ9.99");
    std::cout << "BWZ (zero):     [" << ws_bwz << "]" << std::endl;
    ws_bwz = (ws_small == 0) ? std::string(8, ' ') : cobolEditFmt(static_cast<double>(ws_small), "ZZ,ZZ9.99");
    std::cout << "BWZ (nonzero):  [" << ws_bwz << "]" << std::endl;
    exit(0);
}
