// Transpiled from COBOL program: SIZE-ERROR-TEST
// Generated by Easy COBOL Migrator on 2026-03-23 05:38:13

#include <iostream>
#include <string>
#include <cstdlib>
#include <cstdint>
#include <cstdio>

// COBOL string move helper: truncate or right-pad to field width
inline std::string cobolMove(const std::string& src, int len) {
    std::string r = src; r.resize(len, ' '); return r;
}

// COBOL string comparison: pad shorter operand with spaces
inline int cobolCmp(const std::string& a, const std::string& b) {
    size_t len = std::max(a.size(), b.size());
    std::string la = a, lb = b;
    la.resize(len, ' '); lb.resize(len, ' ');
    return la.compare(lb);
}

// COBOL numeric display: sign, zero-padded integer digits, exact decimal places
inline std::string cobolPicFmt(double val, int intDigits, int decPlaces, bool isSigned) {
    char buf[64];
    if (decPlaces > 0) {
        int w = intDigits + 1 + decPlaces + (isSigned ? 1 : 0);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*.*f" : "%0*.*f", w, decPlaces, val);
    } else {
        auto iv = static_cast<long long>(val);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*lld" : "%0*lld", intDigits + (isSigned ? 1 : 0), iv);
    }
    return std::string(buf);
}
inline std::string cobolPicFmt(int val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}
inline std::string cobolPicFmt(int64_t val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}

namespace size_error_test {

// WORKING-STORAGE variables
int ws_small = 0;
int ws_large = 0;
int ws_signed = 0;
int ws_val_a = 995;
int ws_val_b = 6;
int ws_overflow = 0;

int64_t return_code = 0;

} // namespace size_error_test

int main() {
    using namespace size_error_test;
    std::cout << "=== ON SIZE ERROR TESTS ===" << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>(ws_val_a + ws_val_b);
            if (_temp_result > 999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_small = ws_val_a + ws_val_b;
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case A: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>(ws_val_a + ws_val_b);
            if (_temp_result > 9999999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_large = ws_val_a + ws_val_b;
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case B: WS-LARGE=" << cobolPicFmt(ws_large, 7, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>(ws_val_a * ws_val_b);
            if (_temp_result > 999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_small = ws_val_a * ws_val_b;
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case C: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    ws_overflow = 1;
    std::cout << "Case D: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (0 == 0) _size_error = true;
        if (!_size_error) {
            double _temp_result = static_cast<double>(ws_val_a / 0);
            if (_temp_result > 999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_small = ws_val_a / 0;
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case E: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>((ws_val_a + ws_val_b));
            if (_temp_result > 999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_small = (ws_val_a + ws_val_b);
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case F: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>((5 - 10));
            if (_temp_result > 999.0000000000 || _temp_result < 0.0000000000)
                _size_error = true;
            else
                ws_small = (5 - 10);
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case G: WS-SMALL=" << cobolPicFmt(ws_small, 3, 0, false) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    ws_overflow = 0;
    {  // ON SIZE ERROR guard
        bool _size_error = false;
        if (!_size_error) {
            double _temp_result = static_cast<double>((5 - 10));
            if (_temp_result > 999.0000000000 || _temp_result < -999.0000000000)
                _size_error = true;
            else
                ws_signed = (5 - 10);
        }
        if (_size_error) {
            ws_overflow = 1;
        }
    }
    std::cout << "Case H: WS-SIGNED=" << cobolPicFmt(ws_signed, 3, 0, true) << " overflow=" << cobolPicFmt(ws_overflow, 1, 0, false) << std::endl;
    exit(0);
}
