// Transpiled from COBOL program: COPY-STRUCT
// Generated by Easy COBOL Migrator on 2026-03-23 05:38:29

#include <iostream>
#include <string>
#include <cstdlib>
#include <cstdint>
#include <cstdio>

// COBOL string move helper: truncate or right-pad to field width
inline std::string cobolMove(const std::string& src, int len) {
    std::string r = src; r.resize(len, ' '); return r;
}

// COBOL string comparison: pad shorter operand with spaces
inline int cobolCmp(const std::string& a, const std::string& b) {
    size_t len = std::max(a.size(), b.size());
    std::string la = a, lb = b;
    la.resize(len, ' '); lb.resize(len, ' ');
    return la.compare(lb);
}

// COBOL numeric display: sign, zero-padded integer digits, exact decimal places
inline std::string cobolPicFmt(double val, int intDigits, int decPlaces, bool isSigned) {
    char buf[64];
    if (decPlaces > 0) {
        int w = intDigits + 1 + decPlaces + (isSigned ? 1 : 0);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*.*f" : "%0*.*f", w, decPlaces, val);
    } else {
        auto iv = static_cast<long long>(val);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*lld" : "%0*lld", intDigits + (isSigned ? 1 : 0), iv);
    }
    return std::string(buf);
}
inline std::string cobolPicFmt(int val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}
inline std::string cobolPicFmt(int64_t val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}

namespace copy_struct {

// WORKING-STORAGE variables
struct {
    std::string savings_acct_id = std::string(12, ' ');
    std::string savings_acct_name = std::string(30, ' ');
    double savings_balance = 0.0;
    double savings_int_rate = 0.0;
    std::string savings_status = std::string(1, ' ');
    inline bool savings_active() { return savings_status == "A"; }
    inline bool savings_closed() { return savings_status == "C"; }
    inline bool savings_frozen() { return savings_status == "F"; }
} savings_account;
struct {
    std::string checking_acct_id = std::string(12, ' ');
    std::string checking_acct_name = std::string(30, ' ');
    double checking_balance = 0.0;
    double checking_int_rate = 0.0;
    std::string checking_status = std::string(1, ' ');
    inline bool checking_active() { return checking_status == "A"; }
    inline bool checking_closed() { return checking_status == "C"; }
    inline bool checking_frozen() { return checking_status == "F"; }
} checking_account;
struct {
    std::string credit_acct_id = std::string(12, ' ');
    std::string credit_acct_name = std::string(30, ' ');
    double credit_balance = 0.0;
    double credit_int_rate = 0.0;
    std::string credit_status = std::string(1, ' ');
    inline bool credit_active() { return credit_status == "A"; }
    inline bool credit_closed() { return credit_status == "C"; }
    inline bool credit_frozen() { return credit_status == "F"; }
} credit_account;
double ws_transfer_amt = 0;

int64_t return_code = 0;

} // namespace copy_struct

int main() {
    using namespace copy_struct;
    savings_account.savings_acct_id = cobolMove("SAV-001-2026", 12);
    savings_account.savings_acct_name = cobolMove("Smith, John", 30);
    savings_account.savings_balance = 50000.00;
    savings_account.savings_int_rate = 0.0325;
    savings_account.savings_status = "A";
    checking_account.checking_acct_id = cobolMove("CHK-001-2026", 12);
    checking_account.checking_acct_name = cobolMove("Smith, John", 30);
    checking_account.checking_balance = 12500.00;
    checking_account.checking_int_rate = 0.0010;
    checking_account.checking_status = "A";
    credit_account.credit_acct_id = cobolMove("CRD-001-2026", 12);
    credit_account.credit_acct_name = cobolMove("Smith, John", 30);
    credit_account.credit_balance = -3200.00;
    credit_account.credit_int_rate = 0.1999;
    credit_account.credit_status = "A";
    ws_transfer_amt = 1000.00;
    savings_account.savings_balance = savings_account.savings_balance - (ws_transfer_amt);
    checking_account.checking_balance = checking_account.checking_balance + ws_transfer_amt;
    std::cout << "After transfer of " << cobolPicFmt(ws_transfer_amt, 7, 2, true) << std::endl;
    std::cout << "Savings:  " << cobolPicFmt(savings_account.savings_balance, 7, 2, true) << std::endl;
    std::cout << "Checking: " << cobolPicFmt(checking_account.checking_balance, 7, 2, true) << std::endl;
    std::cout << "Credit:   " << cobolPicFmt(credit_account.credit_balance, 7, 2, true) << std::endl;
    exit(0);
}
