// Transpiled from COBOL program: PACKED-ARITH
// Generated by Easy COBOL Migrator on 2026-03-23 05:37:59

#include <iostream>
#include <string>
#include <cmath>
#include <cstdlib>
#include <cstdint>
#include <cstdio>

// COBOL string move helper: truncate or right-pad to field width
inline std::string cobolMove(const std::string& src, int len) {
    std::string r = src; r.resize(len, ' '); return r;
}

// COBOL string comparison: pad shorter operand with spaces
inline int cobolCmp(const std::string& a, const std::string& b) {
    size_t len = std::max(a.size(), b.size());
    std::string la = a, lb = b;
    la.resize(len, ' '); lb.resize(len, ' ');
    return la.compare(lb);
}

// COBOL numeric display: sign, zero-padded integer digits, exact decimal places
inline std::string cobolPicFmt(double val, int intDigits, int decPlaces, bool isSigned) {
    char buf[64];
    if (decPlaces > 0) {
        int w = intDigits + 1 + decPlaces + (isSigned ? 1 : 0);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*.*f" : "%0*.*f", w, decPlaces, val);
    } else {
        auto iv = static_cast<long long>(val);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*lld" : "%0*lld", intDigits + (isSigned ? 1 : 0), iv);
    }
    return std::string(buf);
}
inline std::string cobolPicFmt(int val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}
inline std::string cobolPicFmt(int64_t val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}

namespace packed_arith {

// WORKING-STORAGE variables
double ws_price = +12345.67;
int ws_qty = 150;
double ws_discount = +0.075;
double ws_tax_rate = +0.1925;
double ws_subtotal = 0;
double ws_discount_amt = 0;
double ws_tax_amt = 0;
double ws_total = 0;
double ws_unit_price = 0;

int64_t return_code = 0;

} // namespace packed_arith

int main() {
    using namespace packed_arith;
    ws_subtotal = std::round((ws_price * ws_qty) * 100.0) / 100.0;
    ws_discount_amt = std::round((ws_subtotal * ws_discount) * 100.0) / 100.0;
    ws_total = ws_subtotal - (ws_discount_amt);
    ws_tax_amt = std::round((ws_total * ws_tax_rate) * 100.0) / 100.0;
    ws_total = ws_total + ws_tax_amt;
    ws_unit_price = std::round((ws_total / ws_qty) * 10000.0) / 10000.0;
    std::cout << "Subtotal:     " << cobolPicFmt(ws_subtotal, 7, 2, true) << std::endl;
    std::cout << "Discount:     " << cobolPicFmt(ws_discount_amt, 7, 2, true) << std::endl;
    std::cout << "Tax:          " << cobolPicFmt(ws_tax_amt, 7, 2, true) << std::endl;
    std::cout << "Total:        " << cobolPicFmt(ws_total, 7, 2, true) << std::endl;
    std::cout << "Unit price:   " << cobolPicFmt(ws_unit_price, 5, 4, true) << std::endl;
    exit(0);
}
