// Transpiled from COBOL program: CALL-PATTERN
// Generated by Easy COBOL Migrator on 2026-03-23 05:38:33

#include <iostream>
#include <string>
#include <cmath>
#include <cstdlib>
#include <cstdint>
#include <cstdio>

// COBOL string move helper: truncate or right-pad to field width
inline std::string cobolMove(const std::string& src, int len) {
    std::string r = src; r.resize(len, ' '); return r;
}

// COBOL string comparison: pad shorter operand with spaces
inline int cobolCmp(const std::string& a, const std::string& b) {
    size_t len = std::max(a.size(), b.size());
    std::string la = a, lb = b;
    la.resize(len, ' '); lb.resize(len, ' ');
    return la.compare(lb);
}

// COBOL numeric display: sign, zero-padded integer digits, exact decimal places
inline std::string cobolPicFmt(double val, int intDigits, int decPlaces, bool isSigned) {
    char buf[64];
    if (decPlaces > 0) {
        int w = intDigits + 1 + decPlaces + (isSigned ? 1 : 0);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*.*f" : "%0*.*f", w, decPlaces, val);
    } else {
        auto iv = static_cast<long long>(val);
        std::snprintf(buf, sizeof(buf), isSigned ? "%+0*lld" : "%0*lld", intDigits + (isSigned ? 1 : 0), iv);
    }
    return std::string(buf);
}
inline std::string cobolPicFmt(int val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}
inline std::string cobolPicFmt(int64_t val, int intDigits, int decPlaces, bool isSigned) {
    return cobolPicFmt(static_cast<double>(val), intDigits, decPlaces, isSigned);
}

namespace call_pattern {

void main_program();
void calc_interest();
void format_name();
void validate_amount();

// WORKING-STORAGE variables
double ws_principal = 0;
double ws_rate = 0;
int ws_years = 0;
double ws_interest = 0;
std::string ws_first_name = "                    ";
std::string ws_last_name = "                    ";
std::string ws_full_name = "                                          ";
double ws_amount = 0;
double ws_min_amount = 0;
double ws_max_amount = 0;
std::string ws_valid_flag = "N";
inline bool ws_is_valid() { return ws_valid_flag == "Y"; }
inline bool ws_is_invalid() { return ws_valid_flag == "N"; }
double ws_total_interest = 0;

int64_t return_code = 0;

void main_program() {
    ws_principal = 50000.00;
    ws_rate = 0.0450;
    ws_years = 5;
    calc_interest();
    std::cout << "Interest (50K, 4.5%, 5yr): " << cobolPicFmt(ws_interest, 7, 2, true) << std::endl;
    ws_total_interest = ws_total_interest + ws_interest;
    ws_principal = 100000.00;
    ws_rate = 0.0325;
    ws_years = 10;
    calc_interest();
    std::cout << "Interest (100K, 3.25%, 10yr): " << cobolPicFmt(ws_interest, 7, 2, true) << std::endl;
    ws_total_interest = ws_total_interest + ws_interest;
    std::cout << "Total interest: " << cobolPicFmt(ws_total_interest, 10, 2, true) << std::endl;
    ws_first_name = cobolMove("John", 20);
    ws_last_name = cobolMove("Smith", 20);
    format_name();
    std::cout << "Formatted: " << ws_full_name << std::endl;
    ws_amount = 5000.00;
    ws_min_amount = 100.00;
    ws_max_amount = 10000.00;
    validate_amount();
    if (ws_is_valid()) {
        std::cout << "Amount 5000.00 is valid" << std::endl;
    } else {
        std::cout << "Amount 5000.00 is invalid" << std::endl;
    }
    ws_amount = 50000.00;
    validate_amount();
    if (ws_is_valid()) {
        std::cout << "Amount 50000.00 is valid" << std::endl;
    } else {
        std::cout << "Amount 50000.00 is invalid" << std::endl;
    }
    exit(0);
}

void calc_interest() {
    ws_interest = std::round((ws_principal * ws_rate) * 100.0) / 100.0;
    ws_years = ws_interest * ws_years;
}

void format_name() {
    {
        std::string _temp;
        { std::string _s(ws_last_name); auto _p = _s.find(" ");
          _temp += (_p != std::string::npos) ? _s.substr(0, _p) : _s; }
        _temp += std::string(", ");
        { std::string _s(ws_first_name); auto _p = _s.find(" ");
          _temp += (_p != std::string::npos) ? _s.substr(0, _p) : _s; }
        ws_full_name = _temp;
    }
}

void validate_amount() {
    ws_valid_flag = "N";
    if ((ws_amount >= ws_min_amount && ws_amount <= ws_max_amount)) {
        ws_valid_flag = "Y";
    }
}

} // namespace call_pattern

int main() {
    using namespace call_pattern;
    main_program();
    return 0;
}
